{
	"COMP_DETAILS":	{
		"JSON_VERS":	"1",
		"EXE_VERS":	"0.03",
		"BPM":	85
	},
	"CHANNELS":	[{
			"CHANNEL_NUM":	0,
			"CONTROL_VALUES":	{
				"GRAPHIC":	"<Default>",
				"SCALE":	101,
				"ALPHA":	33,
				"SPREAD":	43,
				"PARAM":	64,
				"GRAPHIC_2":	"<Default>"
			},
			"CHAN_SET":	{
				"CONLOCK":	false
			},
			"INSTANCES":	[{
					"PRESET_FILE":	"D:\\GameDev\\Games\\VideoCanvas\\Exe\\Data\\Presets\\MilkInternalBasic.elemental",
					"DISPNAME":	"Basic Milk",
					"ACTIVE":	true,
					"CONTROL_VALUES":	{
						"SCALE":	101,
						"ALPHA":	33,
						"SPREAD":	43,
						"PARAM":	64,
						"BLEND":	0
					},
					"CONTENTDATA":	{
						"NAME":	"Basic Milk"
					},
					"ELEMENTS":	[{
							"COMPONENTS":	[]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Milk",
									"PROPERTIES":	[{
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Output",
											"TEXTVALUE":	"Source Channel"
										}, {
											"NAME":	"Preset Selection",
											"TEXTVALUE":	"Random"
										}, {
											"NAME":	"Selection Name",
											"TEXTVALUE":	"martin - cascade.milk"
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	0.998231,
											"RANGE_MIN":	0.781633,
											"RANGE_MAX":	0.998231
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Source"
										}, {
											"NAME":	"Longevity",
											"VALUE":	0.100000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.680272
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0.100000,
											"RANGE_MIN":	-1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1.100000
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	-1.844217,
											"RANGE_MIN":	-2,
											"RANGE_MAX":	2,
											"ENVELOPE":	{
												"MODE":	2,
												"SPEED":	1,
												"KEYFRAMES":	[{
														"TIME":	0,
														"VAL":	0
													}, {
														"TIME":	1,
														"VAL":	1
													}]
											}
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}]
				}, {
					"PRESET_FILE":	"",
					"DISPNAME":	"Basic Fountain",
					"ACTIVE":	false,
					"CONTROL_VALUES":	{
						"SCALE":	10,
						"ALPHA":	16,
						"SPREAD":	64,
						"PARAM":	64,
						"BLEND":	0
					},
					"CONTENTDATA":	{
						"NAME":	"Basic Fountain"
					},
					"ELEMENTS":	[{
							"COMPONENTS":	[]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1,
											"RANGE_MIN":	0.500000,
											"RANGE_MAX":	1.500000
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	4,
											"RANGE_MIN":	4,
											"RANGE_MAX":	10
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0.100000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.500000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"FairyTrailParticle"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	2,
											"RANGE_MIN":	2,
											"RANGE_MAX":	15
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}]
				}, {
					"PRESET_FILE":	"",
					"DISPNAME":	"Circle",
					"ACTIVE":	false,
					"CONTROL_VALUES":	{
						"SCALE":	10,
						"ALPHA":	16,
						"SPREAD":	64,
						"PARAM":	64,
						"BLEND":	0
					},
					"CONTENTDATA":	{
						"NAME":	"Circle"
					},
					"ELEMENTS":	[{
							"COMPONENTS":	[]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1.500000,
											"RANGE_MIN":	1.500000,
											"RANGE_MAX":	2
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	0.300000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0.100000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.500000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1,
											"RANGE_MIN":	0.800000,
											"RANGE_MAX":	1.800000
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	2,
											"RANGE_MIN":	2,
											"RANGE_MAX":	7
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0,
											"RANGE_MIN":	-0.100000,
											"RANGE_MAX":	0.100000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"GlintFloater"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	0.750000,
											"RANGE_MAX":	1.250000
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Circle Path",
									"PROPERTIES":	[{
											"NAME":	"Angle Offset",
											"VALUE":	1.570796
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	1
										}, {
											"NAME":	"Speed",
											"VALUE":	1
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1.500000,
											"RANGE_MIN":	1.500000,
											"RANGE_MAX":	2
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	0.300000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0.100000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.500000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1,
											"RANGE_MIN":	0.800000,
											"RANGE_MAX":	1.800000
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	2,
											"RANGE_MIN":	2,
											"RANGE_MAX":	7
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0,
											"RANGE_MIN":	-0.100000,
											"RANGE_MAX":	0.100000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"GlintFloater"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	0.750000,
											"RANGE_MAX":	1.250000
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Circle Path",
									"PROPERTIES":	[{
											"NAME":	"Angle Offset",
											"VALUE":	3.141593
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	1
										}, {
											"NAME":	"Speed",
											"VALUE":	1
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1.500000,
											"RANGE_MIN":	1.500000,
											"RANGE_MAX":	2
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	0.300000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0.100000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.500000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1,
											"RANGE_MIN":	0.800000,
											"RANGE_MAX":	1.800000
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	2,
											"RANGE_MIN":	2,
											"RANGE_MAX":	7
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0,
											"RANGE_MIN":	-0.100000,
											"RANGE_MAX":	0.100000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"GlintFloater"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	0.750000,
											"RANGE_MAX":	1.250000
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Circle Path",
									"PROPERTIES":	[{
											"NAME":	"Angle Offset",
											"VALUE":	-1.570796
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	1
										}, {
											"NAME":	"Speed",
											"VALUE":	1
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1.500000,
											"RANGE_MIN":	1.500000,
											"RANGE_MAX":	2
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	0.300000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0.100000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.500000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1,
											"RANGE_MIN":	0.800000,
											"RANGE_MAX":	1.800000
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	2,
											"RANGE_MIN":	2,
											"RANGE_MAX":	7
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0,
											"RANGE_MIN":	-0.100000,
											"RANGE_MAX":	0.100000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"GlintFloater"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	0.750000,
											"RANGE_MAX":	1.250000
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Circle Path",
									"PROPERTIES":	[{
											"NAME":	"Angle Offset",
											"VALUE":	0
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	1
										}, {
											"NAME":	"Speed",
											"VALUE":	1
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1.500000,
											"RANGE_MIN":	1.500000,
											"RANGE_MAX":	2
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	0.300000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0.100000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.500000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1,
											"RANGE_MIN":	0.800000,
											"RANGE_MAX":	1.800000
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	2,
											"RANGE_MIN":	2,
											"RANGE_MAX":	7
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0,
											"RANGE_MIN":	-0.100000,
											"RANGE_MAX":	0.100000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"GlintFloater"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	0.750000,
											"RANGE_MAX":	1.250000
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}]
				}, {
					"PRESET_FILE":	"",
					"DISPNAME":	"Basic Left-Right",
					"ACTIVE":	false,
					"CONTROL_VALUES":	{
						"SCALE":	10,
						"ALPHA":	16,
						"SPREAD":	64,
						"PARAM":	64,
						"BLEND":	0
					},
					"CONTENTDATA":	{
						"NAME":	"Basic Left-Right"
					},
					"ELEMENTS":	[{
							"COMPONENTS":	[]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Offset",
									"PROPERTIES":	[{
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"X",
											"VALUE":	0,
											"RANGE_MIN":	-1,
											"RANGE_MAX":	1,
											"ENVELOPE":	{
												"MODE":	2,
												"SPEED":	2,
												"KEYFRAMES":	[{
														"TIME":	0,
														"VAL":	1
													}, {
														"TIME":	1,
														"VAL":	1
													}]
											}
										}, {
											"NAME":	"Y",
											"VALUE":	0,
											"RANGE_MIN":	0,
											"RANGE_MAX":	0
										}, {
											"NAME":	"Z",
											"VALUE":	0,
											"RANGE_MIN":	0,
											"RANGE_MAX":	0
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1.500000,
											"RANGE_MIN":	1.500000,
											"RANGE_MAX":	2
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	0.300000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0.100000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.500000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}]
				}, {
					"PRESET_FILE":	"",
					"DISPNAME":	"Magic Wand",
					"ACTIVE":	false,
					"CONTROL_VALUES":	{
						"SCALE":	10,
						"ALPHA":	16,
						"SPREAD":	64,
						"PARAM":	64,
						"BLEND":	0
					},
					"CONTENTDATA":	{
						"NAME":	"Magic Wand"
					},
					"ELEMENTS":	[{
							"COMPONENTS":	[]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1.500000,
											"RANGE_MIN":	1.500000,
											"RANGE_MAX":	2
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	0.300000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0.100000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.500000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1,
											"RANGE_MIN":	0.800000,
											"RANGE_MAX":	1.800000
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	2,
											"RANGE_MIN":	2,
											"RANGE_MAX":	7
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0,
											"RANGE_MIN":	-0.100000,
											"RANGE_MAX":	0.100000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"GlintFloater"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	0.750000,
											"RANGE_MAX":	1.250000
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}]
				}, {
					"PRESET_FILE":	"",
					"DISPNAME":	"Horiz. Spread",
					"ACTIVE":	false,
					"CONTROL_VALUES":	{
						"SCALE":	10,
						"ALPHA":	16,
						"SPREAD":	64,
						"PARAM":	64,
						"BLEND":	0
					},
					"CONTENTDATA":	{
						"NAME":	"Horiz. Spread"
					},
					"ELEMENTS":	[{
							"COMPONENTS":	[]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Circle Path",
									"PROPERTIES":	[{
											"NAME":	"Angle Offset",
											"VALUE":	0
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	0.500000
										}, {
											"NAME":	"Speed",
											"VALUE":	1
										}]
								}]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Circle Path",
									"PROPERTIES":	[{
											"NAME":	"Angle Offset",
											"VALUE":	3.141593
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	0.500000
										}, {
											"NAME":	"Speed",
											"VALUE":	1
										}]
								}]
						}]
				}]
		}, {
			"CHANNEL_NUM":	1,
			"CONTROL_VALUES":	{
				"GRAPHIC":	"<Default>",
				"SCALE":	88,
				"ALPHA":	14,
				"SPREAD":	64,
				"PARAM":	1,
				"GRAPHIC_2":	"<Default>"
			},
			"CHAN_SET":	{
				"CONLOCK":	false
			},
			"INSTANCES":	[{
					"PRESET_FILE":	"D:\\GameDev\\Games\\VideoCanvas\\Exe\\Data\\Presets\\TrippyBlurredCube.elemental",
					"DISPNAME":	"Default Emitter",
					"ACTIVE":	true,
					"CONTROL_VALUES":	{
						"SCALE":	88,
						"ALPHA":	14,
						"SPREAD":	64,
						"PARAM":	1,
						"BLEND":	0
					},
					"CONTENTDATA":	{
						"NAME":	"Default Emitter"
					},
					"ELEMENTS":	[{
							"COMPONENTS":	[]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Tint",
									"PROPERTIES":	[{
											"NAME":	"A",
											"VALUE":	0.858163,
											"RANGE_MIN":	0.064626,
											"RANGE_MAX":	1,
											"ENVELOPE":	{
												"MODE":	2,
												"SPEED":	2,
												"KEYFRAMES":	[{
														"TIME":	0,
														"VAL":	0
													}, {
														"TIME":	1,
														"VAL":	1
													}]
											}
										}, {
											"NAME":	"B",
											"VALUE":	0.493197,
											"RANGE_MIN":	0.163265,
											"RANGE_MAX":	0.952381
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"G",
											"VALUE":	0.513605,
											"RANGE_MIN":	0.153061,
											"RANGE_MAX":	0.710884
										}, {
											"NAME":	"R",
											"VALUE":	1,
											"RANGE_MIN":	0.170068,
											"RANGE_MAX":	1
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	0.862857,
											"RANGE_MIN":	0.754558,
											"RANGE_MAX":	0.937313
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	0.300000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.800000
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0.100000,
											"RANGE_MIN":	-0.500000,
											"RANGE_MAX":	0.500000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1.097347
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"Set2\\cube1.png"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	0,
											"RANGE_MAX":	0
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	0,
											"RANGE_MAX":	0
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	0,
											"RANGE_MAX":	0
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}]
				}, {
					"PRESET_FILE":	"",
					"DISPNAME":	"Radar Sweep",
					"ACTIVE":	false,
					"CONTROL_VALUES":	{
						"SCALE":	10,
						"ALPHA":	16,
						"SPREAD":	64,
						"PARAM":	64,
						"BLEND":	0
					},
					"CONTENTDATA":	{
						"NAME":	"Radar Sweep"
					},
					"ELEMENTS":	[{
							"COMPONENTS":	[]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Circle Path",
									"PROPERTIES":	[{
											"NAME":	"Angle Offset",
											"VALUE":	0
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	0.250000
										}, {
											"NAME":	"Speed",
											"VALUE":	1
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1,
											"RANGE_MIN":	0.800000,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	5,
											"RANGE_MIN":	5,
											"RANGE_MAX":	9
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.300000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	-0.300000,
											"RANGE_MIN":	-0.700000,
											"RANGE_MAX":	-0.300000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.300000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Circle Path",
									"PROPERTIES":	[{
											"NAME":	"Angle Offset",
											"VALUE":	0
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	0.750000
										}, {
											"NAME":	"Speed",
											"VALUE":	1
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1,
											"RANGE_MIN":	0.800000,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	5,
											"RANGE_MIN":	5,
											"RANGE_MAX":	9
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.300000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	-0.300000,
											"RANGE_MIN":	-0.700000,
											"RANGE_MAX":	-0.300000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.300000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Circle Path",
									"PROPERTIES":	[{
											"NAME":	"Angle Offset",
											"VALUE":	0
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	1.250000
										}, {
											"NAME":	"Speed",
											"VALUE":	1
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1,
											"RANGE_MIN":	0.800000,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	5,
											"RANGE_MIN":	5,
											"RANGE_MAX":	9
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.300000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	-0.300000,
											"RANGE_MIN":	-0.700000,
											"RANGE_MAX":	-0.300000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.300000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Circle Path",
									"PROPERTIES":	[{
											"NAME":	"Angle Offset",
											"VALUE":	0
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	1.750000
										}, {
											"NAME":	"Speed",
											"VALUE":	1
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1,
											"RANGE_MIN":	0.800000,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	5,
											"RANGE_MIN":	5,
											"RANGE_MAX":	9
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.300000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	-0.300000,
											"RANGE_MIN":	-0.700000,
											"RANGE_MAX":	-0.300000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.300000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Circle Path",
									"PROPERTIES":	[{
											"NAME":	"Angle Offset",
											"VALUE":	0
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	2.250000
										}, {
											"NAME":	"Speed",
											"VALUE":	1
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1,
											"RANGE_MIN":	0.800000,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	5,
											"RANGE_MIN":	5,
											"RANGE_MAX":	9
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.300000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	-0.300000,
											"RANGE_MIN":	-0.700000,
											"RANGE_MAX":	-0.300000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.300000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}]
				}, {
					"PRESET_FILE":	"",
					"DISPNAME":	"4x Rising",
					"ACTIVE":	false,
					"CONTROL_VALUES":	{
						"SCALE":	10,
						"ALPHA":	16,
						"SPREAD":	64,
						"PARAM":	64,
						"BLEND":	0
					},
					"CONTENTDATA":	{
						"NAME":	"4x Rising"
					},
					"ELEMENTS":	[{
							"COMPONENTS":	[]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Offset",
									"PROPERTIES":	[{
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"X",
											"VALUE":	-1.500000,
											"RANGE_MIN":	-1.500000,
											"RANGE_MAX":	-1.500000
										}, {
											"NAME":	"Y",
											"VALUE":	0,
											"RANGE_MIN":	0,
											"RANGE_MAX":	0
										}, {
											"NAME":	"Z",
											"VALUE":	0,
											"RANGE_MIN":	0,
											"RANGE_MAX":	0
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1,
											"RANGE_MIN":	0.800000,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	2,
											"RANGE_MIN":	2,
											"RANGE_MAX":	6
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0,
											"RANGE_MIN":	-0.100000,
											"RANGE_MAX":	0.100000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"GravDust"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-2.500000,
											"RANGE_MAX":	2.500000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-2.500000,
											"RANGE_MAX":	2.500000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	0,
											"RANGE_MAX":	4
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Offset",
									"PROPERTIES":	[{
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"X",
											"VALUE":	-0.500000,
											"RANGE_MIN":	-0.500000,
											"RANGE_MAX":	-0.500000
										}, {
											"NAME":	"Y",
											"VALUE":	0,
											"RANGE_MIN":	0,
											"RANGE_MAX":	0
										}, {
											"NAME":	"Z",
											"VALUE":	0,
											"RANGE_MIN":	0,
											"RANGE_MAX":	0
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1,
											"RANGE_MIN":	0.800000,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	2,
											"RANGE_MIN":	2,
											"RANGE_MAX":	6
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0,
											"RANGE_MIN":	-0.100000,
											"RANGE_MAX":	0.100000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"GravDust"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-2.500000,
											"RANGE_MAX":	2.500000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-2.500000,
											"RANGE_MAX":	2.500000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	0,
											"RANGE_MAX":	4
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Offset",
									"PROPERTIES":	[{
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"X",
											"VALUE":	0.500000,
											"RANGE_MIN":	0.500000,
											"RANGE_MAX":	0.500000
										}, {
											"NAME":	"Y",
											"VALUE":	0,
											"RANGE_MIN":	0,
											"RANGE_MAX":	0
										}, {
											"NAME":	"Z",
											"VALUE":	0,
											"RANGE_MIN":	0,
											"RANGE_MAX":	0
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1,
											"RANGE_MIN":	0.800000,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	2,
											"RANGE_MIN":	2,
											"RANGE_MAX":	6
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0,
											"RANGE_MIN":	-0.100000,
											"RANGE_MAX":	0.100000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"GravDust"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-2.500000,
											"RANGE_MAX":	2.500000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-2.500000,
											"RANGE_MAX":	2.500000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	0,
											"RANGE_MAX":	4
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Offset",
									"PROPERTIES":	[{
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"X",
											"VALUE":	1.500000,
											"RANGE_MIN":	1.500000,
											"RANGE_MAX":	1.500000
										}, {
											"NAME":	"Y",
											"VALUE":	0,
											"RANGE_MIN":	0,
											"RANGE_MAX":	0
										}, {
											"NAME":	"Z",
											"VALUE":	0,
											"RANGE_MIN":	0,
											"RANGE_MAX":	0
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1,
											"RANGE_MIN":	0.800000,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	2,
											"RANGE_MIN":	2,
											"RANGE_MAX":	6
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0,
											"RANGE_MIN":	-0.100000,
											"RANGE_MAX":	0.100000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"GravDust"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-2.500000,
											"RANGE_MAX":	2.500000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-2.500000,
											"RANGE_MAX":	2.500000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	0,
											"RANGE_MAX":	4
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}]
				}, {
					"PRESET_FILE":	"",
					"DISPNAME":	"Circle",
					"ACTIVE":	false,
					"CONTROL_VALUES":	{
						"SCALE":	10,
						"ALPHA":	16,
						"SPREAD":	64,
						"PARAM":	64,
						"BLEND":	0
					},
					"CONTENTDATA":	{
						"NAME":	"Circle"
					},
					"ELEMENTS":	[{
							"COMPONENTS":	[]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Circle Path",
									"PROPERTIES":	[{
											"NAME":	"Angle Offset",
											"VALUE":	0
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	0.500000
										}, {
											"NAME":	"Speed",
											"VALUE":	1
										}]
								}]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Circle Path",
									"PROPERTIES":	[{
											"NAME":	"Angle Offset",
											"VALUE":	3.141593
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	0.500000
										}, {
											"NAME":	"Speed",
											"VALUE":	1
										}]
								}]
						}]
				}, {
					"PRESET_FILE":	"",
					"DISPNAME":	"Orbital Glow",
					"ACTIVE":	false,
					"CONTROL_VALUES":	{
						"SCALE":	10,
						"ALPHA":	16,
						"SPREAD":	64,
						"PARAM":	64,
						"BLEND":	0
					},
					"CONTENTDATA":	{
						"NAME":	"Orbital Glow"
					},
					"ELEMENTS":	[{
							"COMPONENTS":	[]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	0.600000,
											"RANGE_MIN":	0.300000,
											"RANGE_MAX":	0.600000
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	5,
											"RANGE_MIN":	5,
											"RANGE_MAX":	9
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"FireStars"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.300000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	-0.300000,
											"RANGE_MIN":	-0.700000,
											"RANGE_MAX":	-0.300000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.300000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Circle Path",
									"PROPERTIES":	[{
											"NAME":	"Angle Offset",
											"VALUE":	0
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	0.750000
										}, {
											"NAME":	"Speed",
											"VALUE":	1
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1.500000,
											"RANGE_MIN":	1.500000,
											"RANGE_MAX":	2
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	0.300000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0.100000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.500000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Circle Path",
									"PROPERTIES":	[{
											"NAME":	"Angle Offset",
											"VALUE":	3.141593
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	0.750000
										}, {
											"NAME":	"Speed",
											"VALUE":	1
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1.500000,
											"RANGE_MIN":	1.500000,
											"RANGE_MAX":	2
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	0.300000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0.100000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.500000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}]
				}, {
					"PRESET_FILE":	"",
					"DISPNAME":	"Offset Switcher",
					"ACTIVE":	false,
					"CONTROL_VALUES":	{
						"SCALE":	10,
						"ALPHA":	16,
						"SPREAD":	64,
						"PARAM":	64,
						"BLEND":	0
					},
					"CONTENTDATA":	{
						"NAME":	"Offset Switcher"
					},
					"ELEMENTS":	[{
							"COMPONENTS":	[]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1.500000,
											"RANGE_MIN":	1.500000,
											"RANGE_MAX":	2
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	0.300000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0.100000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.500000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1,
											"RANGE_MIN":	0.800000,
											"RANGE_MAX":	1.800000
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	2,
											"RANGE_MIN":	2,
											"RANGE_MAX":	7
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0,
											"RANGE_MIN":	-0.100000,
											"RANGE_MAX":	0.100000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"GlintFloater"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	0.750000,
											"RANGE_MAX":	1.250000
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Offset",
									"PROPERTIES":	[{
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"X",
											"VALUE":	0,
											"RANGE_MIN":	0,
											"RANGE_MAX":	0
										}, {
											"NAME":	"Y",
											"VALUE":	0,
											"RANGE_MIN":	0,
											"RANGE_MAX":	0
										}, {
											"NAME":	"Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.900000,
											"RANGE_MAX":	0.900000,
											"ENVELOPE":	{
												"MODE":	1,
												"SPEED":	1,
												"KEYFRAMES":	[{
														"TIME":	0,
														"VAL":	0
													}, {
														"TIME":	0.500000,
														"VAL":	0
													}, {
														"TIME":	0.500000,
														"VAL":	1
													}, {
														"TIME":	1,
														"VAL":	1
													}]
											}
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1.500000,
											"RANGE_MIN":	1.500000,
											"RANGE_MAX":	2
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	0.300000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0.100000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.500000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1,
											"RANGE_MIN":	0.800000,
											"RANGE_MAX":	1.800000
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	2,
											"RANGE_MIN":	2,
											"RANGE_MAX":	7
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0,
											"RANGE_MIN":	-0.100000,
											"RANGE_MAX":	0.100000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"GlintFloater"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	0.750000,
											"RANGE_MAX":	1.250000
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}]
				}]
		}, {
			"CHANNEL_NUM":	2,
			"CONTROL_VALUES":	{
				"GRAPHIC":	"<Default>",
				"SCALE":	70,
				"ALPHA":	6,
				"SPREAD":	13,
				"PARAM":	64,
				"GRAPHIC_2":	"<Default>"
			},
			"CHAN_SET":	{
				"CONLOCK":	false
			},
			"INSTANCES":	[{
					"PRESET_FILE":	"D:\\GameDev\\Games\\VideoCanvas\\Exe\\Data\\Presets\\GeissColourCycleBasic.elemental",
					"DISPNAME":	"Default Emitter",
					"ACTIVE":	false,
					"CONTROL_VALUES":	{
						"SCALE":	88,
						"ALPHA":	66,
						"SPREAD":	64,
						"PARAM":	2,
						"BLEND":	0
					},
					"CONTENTDATA":	{
						"NAME":	"Default Emitter"
					},
					"ELEMENTS":	[{
							"COMPONENTS":	[]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Tint",
									"PROPERTIES":	[{
											"NAME":	"A",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"B",
											"VALUE":	0.474804,
											"RANGE_MIN":	0.142857,
											"RANGE_MAX":	1,
											"ENVELOPE":	{
												"MODE":	2,
												"SPEED":	4,
												"KEYFRAMES":	[{
														"TIME":	0,
														"VAL":	0
													}, {
														"TIME":	1,
														"VAL":	1
													}]
											}
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"G",
											"VALUE":	0.765857,
											"RANGE_MIN":	0,
											"RANGE_MAX":	1,
											"ENVELOPE":	{
												"MODE":	2,
												"SPEED":	0.500000,
												"KEYFRAMES":	[{
														"TIME":	0,
														"VAL":	0
													}, {
														"TIME":	1,
														"VAL":	1
													}]
											}
										}, {
											"NAME":	"R",
											"VALUE":	0.436422,
											"RANGE_MIN":	0.214286,
											"RANGE_MAX":	1,
											"ENVELOPE":	{
												"MODE":	2,
												"SPEED":	1,
												"KEYFRAMES":	[{
														"TIME":	0,
														"VAL":	0
													}, {
														"TIME":	1,
														"VAL":	1
													}]
											}
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	0.889932,
											"RANGE_MIN":	0.889932,
											"RANGE_MAX":	1.140374
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	0.300000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.500000
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0.100000,
											"RANGE_MIN":	-4,
											"RANGE_MAX":	4
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1.097347
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"geiss1.png"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-5,
											"RANGE_MAX":	5
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	0,
											"RANGE_MAX":	0
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	0,
											"RANGE_MAX":	0
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}]
				}, {
					"PRESET_FILE":	"D:\\GameDev\\Games\\VideoCanvas\\Exe\\Data\\Presets\\Circle.elemental",
					"DISPNAME":	"Circle",
					"ACTIVE":	true,
					"CONTROL_VALUES":	{
						"SCALE":	70,
						"ALPHA":	6,
						"SPREAD":	13,
						"PARAM":	64,
						"BLEND":	0
					},
					"CONTENTDATA":	{
						"NAME":	"Circle"
					},
					"ELEMENTS":	[{
							"COMPONENTS":	[]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1.500000,
											"RANGE_MIN":	1.500000,
											"RANGE_MAX":	2
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	0.300000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0.100000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.500000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1,
											"RANGE_MIN":	0.800000,
											"RANGE_MAX":	1.800000
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	2,
											"RANGE_MIN":	2,
											"RANGE_MAX":	7
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0,
											"RANGE_MIN":	-0.100000,
											"RANGE_MAX":	0.100000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"GlintFloater"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	0.750000,
											"RANGE_MAX":	1.250000
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Circle Path",
									"PROPERTIES":	[{
											"NAME":	"Angle Offset",
											"VALUE":	1.570796
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	1
										}, {
											"NAME":	"Speed",
											"VALUE":	1
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1.500000,
											"RANGE_MIN":	1.500000,
											"RANGE_MAX":	2
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	0.300000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0.100000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.500000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1,
											"RANGE_MIN":	0.800000,
											"RANGE_MAX":	1.800000
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	2,
											"RANGE_MIN":	2,
											"RANGE_MAX":	7
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0,
											"RANGE_MIN":	-0.100000,
											"RANGE_MAX":	0.100000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"GlintFloater"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	0.750000,
											"RANGE_MAX":	1.250000
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Circle Path",
									"PROPERTIES":	[{
											"NAME":	"Angle Offset",
											"VALUE":	3.141593
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	1
										}, {
											"NAME":	"Speed",
											"VALUE":	1
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1.500000,
											"RANGE_MIN":	1.500000,
											"RANGE_MAX":	2
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	0.300000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0.100000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.500000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1,
											"RANGE_MIN":	0.800000,
											"RANGE_MAX":	1.800000
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	2,
											"RANGE_MIN":	2,
											"RANGE_MAX":	7
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0,
											"RANGE_MIN":	-0.100000,
											"RANGE_MAX":	0.100000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"GlintFloater"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	0.750000,
											"RANGE_MAX":	1.250000
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Circle Path",
									"PROPERTIES":	[{
											"NAME":	"Angle Offset",
											"VALUE":	-1.570796
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	1
										}, {
											"NAME":	"Speed",
											"VALUE":	1
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1.500000,
											"RANGE_MIN":	1.500000,
											"RANGE_MAX":	2
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	0.300000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0.100000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.500000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1,
											"RANGE_MIN":	0.800000,
											"RANGE_MAX":	1.800000
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	2,
											"RANGE_MIN":	2,
											"RANGE_MAX":	7
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0,
											"RANGE_MIN":	-0.100000,
											"RANGE_MAX":	0.100000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"GlintFloater"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	0.750000,
											"RANGE_MAX":	1.250000
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Circle Path",
									"PROPERTIES":	[{
											"NAME":	"Angle Offset",
											"VALUE":	0
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	1
										}, {
											"NAME":	"Speed",
											"VALUE":	1
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1.500000,
											"RANGE_MIN":	1.500000,
											"RANGE_MAX":	2
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	0.300000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0.100000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.500000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1,
											"RANGE_MIN":	0.800000,
											"RANGE_MAX":	1.800000
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	2,
											"RANGE_MIN":	2,
											"RANGE_MAX":	7
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0,
											"RANGE_MIN":	-0.100000,
											"RANGE_MAX":	0.100000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"GlintFloater"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	0.750000,
											"RANGE_MAX":	1.250000
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}]
				}, {
					"PRESET_FILE":	"",
					"DISPNAME":	"Offset Switcher",
					"ACTIVE":	false,
					"CONTROL_VALUES":	{
						"SCALE":	10,
						"ALPHA":	16,
						"SPREAD":	64,
						"PARAM":	64,
						"BLEND":	0
					},
					"CONTENTDATA":	{
						"NAME":	"Offset Switcher"
					},
					"ELEMENTS":	[{
							"COMPONENTS":	[]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1.500000,
											"RANGE_MIN":	1.500000,
											"RANGE_MAX":	2
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	0.300000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0.100000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.500000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1,
											"RANGE_MIN":	0.800000,
											"RANGE_MAX":	1.800000
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	2,
											"RANGE_MIN":	2,
											"RANGE_MAX":	7
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0,
											"RANGE_MIN":	-0.100000,
											"RANGE_MAX":	0.100000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"GlintFloater"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	0.750000,
											"RANGE_MAX":	1.250000
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Offset",
									"PROPERTIES":	[{
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"X",
											"VALUE":	0,
											"RANGE_MIN":	0,
											"RANGE_MAX":	0
										}, {
											"NAME":	"Y",
											"VALUE":	0,
											"RANGE_MIN":	0,
											"RANGE_MAX":	0
										}, {
											"NAME":	"Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.900000,
											"RANGE_MAX":	0.900000,
											"ENVELOPE":	{
												"MODE":	1,
												"SPEED":	1,
												"KEYFRAMES":	[{
														"TIME":	0,
														"VAL":	0
													}, {
														"TIME":	0.500000,
														"VAL":	0
													}, {
														"TIME":	0.500000,
														"VAL":	1
													}, {
														"TIME":	1,
														"VAL":	1
													}]
											}
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1.500000,
											"RANGE_MIN":	1.500000,
											"RANGE_MAX":	2
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	0.300000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0.100000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.500000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1,
											"RANGE_MIN":	0.800000,
											"RANGE_MAX":	1.800000
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	2,
											"RANGE_MIN":	2,
											"RANGE_MAX":	7
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0,
											"RANGE_MIN":	-0.100000,
											"RANGE_MAX":	0.100000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"GlintFloater"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	0.750000,
											"RANGE_MAX":	1.250000
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}]
				}, {
					"PRESET_FILE":	"",
					"DISPNAME":	"Default Emitter",
					"ACTIVE":	false,
					"CONTROL_VALUES":	{
						"SCALE":	10,
						"ALPHA":	16,
						"SPREAD":	64,
						"PARAM":	64,
						"BLEND":	0
					},
					"CONTENTDATA":	{
						"NAME":	"Default Emitter"
					},
					"ELEMENTS":	[{
							"COMPONENTS":	[]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1.500000,
											"RANGE_MIN":	1.500000,
											"RANGE_MAX":	2
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	0.300000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0.100000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.500000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}]
				}, {
					"PRESET_FILE":	"",
					"DISPNAME":	"Basic Fountain",
					"ACTIVE":	false,
					"CONTROL_VALUES":	{
						"SCALE":	10,
						"ALPHA":	16,
						"SPREAD":	64,
						"PARAM":	64,
						"BLEND":	0
					},
					"CONTENTDATA":	{
						"NAME":	"Basic Fountain"
					},
					"ELEMENTS":	[{
							"COMPONENTS":	[]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1,
											"RANGE_MIN":	0.500000,
											"RANGE_MAX":	1.500000
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	4,
											"RANGE_MIN":	4,
											"RANGE_MAX":	10
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0.100000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.500000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"FairyTrailParticle"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	2,
											"RANGE_MIN":	2,
											"RANGE_MAX":	15
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}]
				}, {
					"PRESET_FILE":	"",
					"DISPNAME":	"Circle",
					"ACTIVE":	false,
					"CONTROL_VALUES":	{
						"SCALE":	10,
						"ALPHA":	16,
						"SPREAD":	64,
						"PARAM":	64,
						"BLEND":	0
					},
					"CONTENTDATA":	{
						"NAME":	"Circle"
					},
					"ELEMENTS":	[{
							"COMPONENTS":	[]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1.500000,
											"RANGE_MIN":	1.500000,
											"RANGE_MAX":	2
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	0.300000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0.100000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.500000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1,
											"RANGE_MIN":	0.800000,
											"RANGE_MAX":	1.800000
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	2,
											"RANGE_MIN":	2,
											"RANGE_MAX":	7
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0,
											"RANGE_MIN":	-0.100000,
											"RANGE_MAX":	0.100000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"GlintFloater"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	0.750000,
											"RANGE_MAX":	1.250000
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Circle Path",
									"PROPERTIES":	[{
											"NAME":	"Angle Offset",
											"VALUE":	1.570796
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	1
										}, {
											"NAME":	"Speed",
											"VALUE":	1
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1.500000,
											"RANGE_MIN":	1.500000,
											"RANGE_MAX":	2
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	0.300000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0.100000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.500000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1,
											"RANGE_MIN":	0.800000,
											"RANGE_MAX":	1.800000
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	2,
											"RANGE_MIN":	2,
											"RANGE_MAX":	7
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0,
											"RANGE_MIN":	-0.100000,
											"RANGE_MAX":	0.100000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"GlintFloater"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	0.750000,
											"RANGE_MAX":	1.250000
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Circle Path",
									"PROPERTIES":	[{
											"NAME":	"Angle Offset",
											"VALUE":	3.141593
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	1
										}, {
											"NAME":	"Speed",
											"VALUE":	1
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1.500000,
											"RANGE_MIN":	1.500000,
											"RANGE_MAX":	2
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	0.300000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0.100000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.500000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1,
											"RANGE_MIN":	0.800000,
											"RANGE_MAX":	1.800000
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	2,
											"RANGE_MIN":	2,
											"RANGE_MAX":	7
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0,
											"RANGE_MIN":	-0.100000,
											"RANGE_MAX":	0.100000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"GlintFloater"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	0.750000,
											"RANGE_MAX":	1.250000
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Circle Path",
									"PROPERTIES":	[{
											"NAME":	"Angle Offset",
											"VALUE":	-1.570796
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	1
										}, {
											"NAME":	"Speed",
											"VALUE":	1
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1.500000,
											"RANGE_MIN":	1.500000,
											"RANGE_MAX":	2
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	0.300000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0.100000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.500000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1,
											"RANGE_MIN":	0.800000,
											"RANGE_MAX":	1.800000
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	2,
											"RANGE_MIN":	2,
											"RANGE_MAX":	7
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0,
											"RANGE_MIN":	-0.100000,
											"RANGE_MAX":	0.100000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"GlintFloater"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	0.750000,
											"RANGE_MAX":	1.250000
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Circle Path",
									"PROPERTIES":	[{
											"NAME":	"Angle Offset",
											"VALUE":	0
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	1
										}, {
											"NAME":	"Speed",
											"VALUE":	1
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1.500000,
											"RANGE_MIN":	1.500000,
											"RANGE_MAX":	2
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	0.300000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0.100000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.500000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1,
											"RANGE_MIN":	0.800000,
											"RANGE_MAX":	1.800000
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	2,
											"RANGE_MIN":	2,
											"RANGE_MAX":	7
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0,
											"RANGE_MIN":	-0.100000,
											"RANGE_MAX":	0.100000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"GlintFloater"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	0.750000,
											"RANGE_MAX":	1.250000
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}]
				}]
		}, {
			"CHANNEL_NUM":	3,
			"CONTROL_VALUES":	{
				"GRAPHIC":	"Firework",
				"SCALE":	61,
				"ALPHA":	10,
				"SPREAD":	31,
				"PARAM":	73,
				"GRAPHIC_2":	"<Default>"
			},
			"CHAN_SET":	{
				"CONLOCK":	false
			},
			"INSTANCES":	[{
					"PRESET_FILE":	"D:\\GameDev\\Games\\VideoCanvas\\Exe\\Data\\Presets\\RedElectromagneticSpinner.elemental",
					"DISPNAME":	"Red EM Spinner",
					"ACTIVE":	true,
					"CONTROL_VALUES":	{
						"GRAPHIC":	"Firework",
						"SCALE":	61,
						"ALPHA":	10,
						"SPREAD":	31,
						"PARAM":	73,
						"BLEND":	0
					},
					"CONTENTDATA":	{
						"NAME":	"Red EM Spinner"
					},
					"ELEMENTS":	[{
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	0.600000,
											"RANGE_MIN":	0.300000,
											"RANGE_MAX":	0.600000
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	5,
											"RANGE_MIN":	5,
											"RANGE_MAX":	9
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"SpecialEffectParticle1"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#2 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"FireStars"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.300000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	-0.300000,
											"RANGE_MIN":	-0.700000,
											"RANGE_MAX":	-0.300000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.300000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Circle Path",
									"PROPERTIES":	[{
											"NAME":	"Angle Offset",
											"VALUE":	0
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	0.750000
										}, {
											"NAME":	"Speed",
											"VALUE":	1
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1.500000,
											"RANGE_MIN":	1.500000,
											"RANGE_MAX":	2
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	0.300000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0.100000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.500000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	6.798077
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Circle Path",
									"PROPERTIES":	[{
											"NAME":	"Angle Offset",
											"VALUE":	3.141593
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	0.750000
										}, {
											"NAME":	"Speed",
											"VALUE":	1
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1.500000,
											"RANGE_MIN":	1.500000,
											"RANGE_MAX":	2
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	0.300000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0.100000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.500000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	6.413846
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}]
				}, {
					"PRESET_FILE":	"",
					"DISPNAME":	"Radar Sweep",
					"ACTIVE":	false,
					"CONTROL_VALUES":	{
						"SCALE":	10,
						"ALPHA":	16,
						"SPREAD":	64,
						"PARAM":	64,
						"BLEND":	0
					},
					"CONTENTDATA":	{
						"NAME":	"Radar Sweep"
					},
					"ELEMENTS":	[{
							"COMPONENTS":	[]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Circle Path",
									"PROPERTIES":	[{
											"NAME":	"Angle Offset",
											"VALUE":	0
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	0.250000
										}, {
											"NAME":	"Speed",
											"VALUE":	1
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1,
											"RANGE_MIN":	0.800000,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	5,
											"RANGE_MIN":	5,
											"RANGE_MAX":	9
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.300000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	-0.300000,
											"RANGE_MIN":	-0.700000,
											"RANGE_MAX":	-0.300000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.300000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Circle Path",
									"PROPERTIES":	[{
											"NAME":	"Angle Offset",
											"VALUE":	0
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	0.750000
										}, {
											"NAME":	"Speed",
											"VALUE":	1
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1,
											"RANGE_MIN":	0.800000,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	5,
											"RANGE_MIN":	5,
											"RANGE_MAX":	9
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.300000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	-0.300000,
											"RANGE_MIN":	-0.700000,
											"RANGE_MAX":	-0.300000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.300000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Circle Path",
									"PROPERTIES":	[{
											"NAME":	"Angle Offset",
											"VALUE":	0
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	1.250000
										}, {
											"NAME":	"Speed",
											"VALUE":	1
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1,
											"RANGE_MIN":	0.800000,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	5,
											"RANGE_MIN":	5,
											"RANGE_MAX":	9
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.300000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	-0.300000,
											"RANGE_MIN":	-0.700000,
											"RANGE_MAX":	-0.300000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.300000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Circle Path",
									"PROPERTIES":	[{
											"NAME":	"Angle Offset",
											"VALUE":	0
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	1.750000
										}, {
											"NAME":	"Speed",
											"VALUE":	1
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1,
											"RANGE_MIN":	0.800000,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	5,
											"RANGE_MIN":	5,
											"RANGE_MAX":	9
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.300000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	-0.300000,
											"RANGE_MIN":	-0.700000,
											"RANGE_MAX":	-0.300000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.300000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Circle Path",
									"PROPERTIES":	[{
											"NAME":	"Angle Offset",
											"VALUE":	0
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	2.250000
										}, {
											"NAME":	"Speed",
											"VALUE":	1
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1,
											"RANGE_MIN":	0.800000,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	5,
											"RANGE_MIN":	5,
											"RANGE_MAX":	9
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.300000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	-0.300000,
											"RANGE_MIN":	-0.700000,
											"RANGE_MAX":	-0.300000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.300000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}]
				}, {
					"PRESET_FILE":	"",
					"DISPNAME":	"4x Rising",
					"ACTIVE":	false,
					"CONTROL_VALUES":	{
						"SCALE":	10,
						"ALPHA":	16,
						"SPREAD":	64,
						"PARAM":	64,
						"BLEND":	0
					},
					"CONTENTDATA":	{
						"NAME":	"4x Rising"
					},
					"ELEMENTS":	[{
							"COMPONENTS":	[]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Offset",
									"PROPERTIES":	[{
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"X",
											"VALUE":	-1.500000,
											"RANGE_MIN":	-1.500000,
											"RANGE_MAX":	-1.500000
										}, {
											"NAME":	"Y",
											"VALUE":	0,
											"RANGE_MIN":	0,
											"RANGE_MAX":	0
										}, {
											"NAME":	"Z",
											"VALUE":	0,
											"RANGE_MIN":	0,
											"RANGE_MAX":	0
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1,
											"RANGE_MIN":	0.800000,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	2,
											"RANGE_MIN":	2,
											"RANGE_MAX":	6
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0,
											"RANGE_MIN":	-0.100000,
											"RANGE_MAX":	0.100000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"GravDust"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-2.500000,
											"RANGE_MAX":	2.500000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-2.500000,
											"RANGE_MAX":	2.500000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	0,
											"RANGE_MAX":	4
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Offset",
									"PROPERTIES":	[{
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"X",
											"VALUE":	-0.500000,
											"RANGE_MIN":	-0.500000,
											"RANGE_MAX":	-0.500000
										}, {
											"NAME":	"Y",
											"VALUE":	0,
											"RANGE_MIN":	0,
											"RANGE_MAX":	0
										}, {
											"NAME":	"Z",
											"VALUE":	0,
											"RANGE_MIN":	0,
											"RANGE_MAX":	0
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1,
											"RANGE_MIN":	0.800000,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	2,
											"RANGE_MIN":	2,
											"RANGE_MAX":	6
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0,
											"RANGE_MIN":	-0.100000,
											"RANGE_MAX":	0.100000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"GravDust"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-2.500000,
											"RANGE_MAX":	2.500000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-2.500000,
											"RANGE_MAX":	2.500000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	0,
											"RANGE_MAX":	4
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Offset",
									"PROPERTIES":	[{
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"X",
											"VALUE":	0.500000,
											"RANGE_MIN":	0.500000,
											"RANGE_MAX":	0.500000
										}, {
											"NAME":	"Y",
											"VALUE":	0,
											"RANGE_MIN":	0,
											"RANGE_MAX":	0
										}, {
											"NAME":	"Z",
											"VALUE":	0,
											"RANGE_MIN":	0,
											"RANGE_MAX":	0
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1,
											"RANGE_MIN":	0.800000,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	2,
											"RANGE_MIN":	2,
											"RANGE_MAX":	6
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0,
											"RANGE_MIN":	-0.100000,
											"RANGE_MAX":	0.100000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"GravDust"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-2.500000,
											"RANGE_MAX":	2.500000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-2.500000,
											"RANGE_MAX":	2.500000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	0,
											"RANGE_MAX":	4
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Offset",
									"PROPERTIES":	[{
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"X",
											"VALUE":	1.500000,
											"RANGE_MIN":	1.500000,
											"RANGE_MAX":	1.500000
										}, {
											"NAME":	"Y",
											"VALUE":	0,
											"RANGE_MIN":	0,
											"RANGE_MAX":	0
										}, {
											"NAME":	"Z",
											"VALUE":	0,
											"RANGE_MIN":	0,
											"RANGE_MAX":	0
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1,
											"RANGE_MIN":	0.800000,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	2,
											"RANGE_MIN":	2,
											"RANGE_MAX":	6
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0,
											"RANGE_MIN":	-0.100000,
											"RANGE_MAX":	0.100000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"GravDust"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-2.500000,
											"RANGE_MAX":	2.500000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-2.500000,
											"RANGE_MAX":	2.500000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	0,
											"RANGE_MAX":	4
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}]
				}, {
					"PRESET_FILE":	"",
					"DISPNAME":	"Circle",
					"ACTIVE":	false,
					"CONTROL_VALUES":	{
						"SCALE":	10,
						"ALPHA":	16,
						"SPREAD":	64,
						"PARAM":	64,
						"BLEND":	0
					},
					"CONTENTDATA":	{
						"NAME":	"Circle"
					},
					"ELEMENTS":	[{
							"COMPONENTS":	[]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Circle Path",
									"PROPERTIES":	[{
											"NAME":	"Angle Offset",
											"VALUE":	0
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	0.500000
										}, {
											"NAME":	"Speed",
											"VALUE":	1
										}]
								}]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Circle Path",
									"PROPERTIES":	[{
											"NAME":	"Angle Offset",
											"VALUE":	3.141593
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	0.500000
										}, {
											"NAME":	"Speed",
											"VALUE":	1
										}]
								}]
						}]
				}, {
					"PRESET_FILE":	"",
					"DISPNAME":	"Orbital Glow",
					"ACTIVE":	false,
					"CONTROL_VALUES":	{
						"SCALE":	10,
						"ALPHA":	16,
						"SPREAD":	64,
						"PARAM":	64,
						"BLEND":	0
					},
					"CONTENTDATA":	{
						"NAME":	"Orbital Glow"
					},
					"ELEMENTS":	[{
							"COMPONENTS":	[]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	0.600000,
											"RANGE_MIN":	0.300000,
											"RANGE_MAX":	0.600000
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	5,
											"RANGE_MIN":	5,
											"RANGE_MAX":	9
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"FireStars"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.300000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	-0.300000,
											"RANGE_MIN":	-0.700000,
											"RANGE_MAX":	-0.300000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.300000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Circle Path",
									"PROPERTIES":	[{
											"NAME":	"Angle Offset",
											"VALUE":	0
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	0.750000
										}, {
											"NAME":	"Speed",
											"VALUE":	1
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1.500000,
											"RANGE_MIN":	1.500000,
											"RANGE_MAX":	2
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	0.300000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0.100000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.500000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Circle Path",
									"PROPERTIES":	[{
											"NAME":	"Angle Offset",
											"VALUE":	3.141593
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Scale",
											"VALUE":	0.750000
										}, {
											"NAME":	"Speed",
											"VALUE":	1
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1.500000,
											"RANGE_MIN":	1.500000,
											"RANGE_MAX":	2
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	0.300000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0.100000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.500000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}]
				}, {
					"PRESET_FILE":	"",
					"DISPNAME":	"Offset Switcher",
					"ACTIVE":	false,
					"CONTROL_VALUES":	{
						"SCALE":	10,
						"ALPHA":	16,
						"SPREAD":	64,
						"PARAM":	64,
						"BLEND":	0
					},
					"CONTENTDATA":	{
						"NAME":	"Offset Switcher"
					},
					"ELEMENTS":	[{
							"COMPONENTS":	[]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1.500000,
											"RANGE_MIN":	1.500000,
											"RANGE_MAX":	2
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	0.300000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0.100000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.500000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1,
											"RANGE_MIN":	0.800000,
											"RANGE_MAX":	1.800000
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	2,
											"RANGE_MIN":	2,
											"RANGE_MAX":	7
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0,
											"RANGE_MIN":	-0.100000,
											"RANGE_MAX":	0.100000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"GlintFloater"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	0.750000,
											"RANGE_MAX":	1.250000
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}, {
							"COMPONENTS":	[{
									"COMPONENT_TYPE":	"Offset",
									"PROPERTIES":	[{
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"X",
											"VALUE":	0,
											"RANGE_MIN":	0,
											"RANGE_MAX":	0
										}, {
											"NAME":	"Y",
											"VALUE":	0,
											"RANGE_MIN":	0,
											"RANGE_MAX":	0
										}, {
											"NAME":	"Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.900000,
											"RANGE_MAX":	0.900000,
											"ENVELOPE":	{
												"MODE":	1,
												"SPEED":	1,
												"KEYFRAMES":	[{
														"TIME":	0,
														"VAL":	0
													}, {
														"TIME":	0.500000,
														"VAL":	0
													}, {
														"TIME":	0.500000,
														"VAL":	1
													}, {
														"TIME":	1,
														"VAL":	1
													}]
											}
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1.500000,
											"RANGE_MIN":	1.500000,
											"RANGE_MAX":	2
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	0.300000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.300000
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0.100000,
											"RANGE_MIN":	0.100000,
											"RANGE_MAX":	0.500000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"BasicGlow"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	1,
											"RANGE_MAX":	1
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"#1 Channel Graphic"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.200000,
											"RANGE_MAX":	0.200000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}, {
									"COMPONENT_TYPE":	"Particle Emitter",
									"PROPERTIES":	[{
											"NAME":	"Alpha",
											"VALUE":	1,
											"RANGE_MIN":	0.800000,
											"RANGE_MAX":	1.800000
										}, {
											"NAME":	"Bypass",
											"VALUE":	0
										}, {
											"NAME":	"Emit Freq",
											"VALUE":	60,
											"RANGE_MIN":	60,
											"RANGE_MAX":	60
										}, {
											"NAME":	"Graphic Type",
											"TEXTVALUE":	"Sprite"
										}, {
											"NAME":	"Longevity",
											"VALUE":	2,
											"RANGE_MIN":	2,
											"RANGE_MAX":	7
										}, {
											"NAME":	"Model Source",
											"TEXTVALUE":	"Sphere.atm"
										}, {
											"NAME":	"Particle Rot Speed",
											"VALUE":	0,
											"RANGE_MIN":	-0.100000,
											"RANGE_MAX":	0.100000
										}, {
											"NAME":	"Particle Type",
											"TEXTVALUE":	"GlintFloater"
										}, {
											"NAME":	"Random Init Rot",
											"VALUE":	1
										}, {
											"NAME":	"Scale",
											"VALUE":	1,
											"RANGE_MIN":	0.750000,
											"RANGE_MAX":	1.250000
										}, {
											"NAME":	"Source Channel",
											"TEXTVALUE":	""
										}, {
											"NAME":	"Spout Source",
											"TEXTVALUE":	"NestDrop Deck 1"
										}, {
											"NAME":	"Sprite",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Sprite (Default)",
											"TEXTVALUE":	"SunGlow"
										}, {
											"NAME":	"Vel X",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"Vel Y",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"Vel Z",
											"VALUE":	0,
											"RANGE_MIN":	-0.075000,
											"RANGE_MAX":	0.075000
										}, {
											"NAME":	"VelX Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelY Param Mod",
											"VALUE":	0
										}, {
											"NAME":	"VelZ Param Mod",
											"VALUE":	0
										}]
								}]
						}]
				}]
		}]
}